### ISSUE TITLE
using router5 link in react-redux

### ISSUE THREAD

**Issue by svnm** [router5/examples#5] opened 2015-11-16 11:43 UTC
I just opened a pull request to use deku-router5 Link component. I am not sure it was the correct way to use deku-router5 Link but it seemed to work okay.

For the [react-redux example](https://github.com/StevenIseki/examples/tree/master/apps/react-redux) I would like to see how we can use the  react-router5 Link component.

I tried the following but came up with an error: `Uncaught TypeError: this.router.addListener is not a function`

``` js
import React, { Component, PropTypes } from 'react';
import { Link } from 'react-router5';

class Nav extends Component {
    constructor(props, context) {
        super(props);
    }

    render() {

        return (
            <nav>
                <Link routeName='inbox' routeOptions={{ reload: true }}>Inbox</Link>
                <Link routeName='compose'>Compose</Link>
                <Link routeName='contacts'>Contacts</Link>
            </nav>
        );
    }
}

export default Nav;
```

Thanks

**Comment by troch** [comment] 2015-11-16 11:52
You shouldn't (need to) use react-router5 Link with react-redux, and you shouldn't (need to) use deku-router5 Link with deku-redux.

react-router5 uses the listeners plugin to be notified by route changes, and update itself. It receives state updates directly from the router. When using redux, you get state updates from your store, and you don't need (shouldn't use) stateful components like `Link`. The error you get is because `router5-listeners` package is not used (and should not be used, otherwise **you bypass your store which should be the only source of truth**).

Same thing is true with deku-router5, although deku-router5 `Link` component is not stateful but receives prop updates from the source `route`. With deku-redux, your links should only receive state updates / prop updates from the store, not by a route value set on your tree.

**without redux**:
- deku-router5
- react-router5

**with redux**:
(notice how redux is between deku/react and router5)
- deku-redux + redux-router5
- react-redux + redux-router5

**Comment by svnm** [comment] 2015-11-16 12:07
Okay that makes sense, so they are stateful components and should not be used with redux. 

Would it make sense to add a Link component to deku-redux and react-redux? Would each [Link component](https://github.com/router5/examples/blob/master/apps/deku-redux/components/Link.js) in a redux app be exactly the same, hence it is just boilerplate.

**Comment by troch** [comment] 2015-11-16 12:25
Well I think it would make sense to add a Link component which would remove the boilerplate of getting the router from source (Deku) or context (React) and building an href with a route name and route params.

However, they are three ways links can be used which leads to different implementations
- Links receive as a prop if they are active or not (typically in a menu which uses `connect`)
- Links receive the active route as a prop (with `connect`) and figure out if they are active (typically for a link which would be on its own)
- Links can have no active property / DOM state (active class name)

What they have in common: they need to compute their href.

But:
- It cannot be in react-deux or deku-redux because they have nothing to do with router5.
- It cannot be in react-router5 or deku-router5 because they already have their Link component which shouldn't be used with redux.
- It shouldn't be in redux-router5 because it has no ties with React or Deku

So it would be in a repository called
- react-redux-router5
- deku-redux-router5

:laughing:

**Comment by svnm** [comment] 2015-11-17 00:25
So the link component in **react-router5** and **deku-router5** cannot have support for redux?

I do notice in my [react-router-redux example](https://github.com/StevenIseki/redux-examples/blob/master/redux-react-router/src/App.js) which was very similar to the official example, the only one I could find actually... the Link component from react-router is used, however it imports pushState from **redux-router**. So it is not needed with react-router to include an additional dependancy, however this may because react-router's redux integration [redux-router](https://github.com/rackt/redux-router) is specific to react whereas [redux-router5](https://github.com/router5/redux-router5) is not.

It would be great if we do not need to add additional repos **react-redux-router5** and **deku-redux-router5** as that would be very confusing as there is already [redux-router5 repo](https://github.com/router5/redux-router5) which deals with the integration of redux with router5. 

Unless I misunderstand and you mean that we could possibly split [redux-router5 repo](https://github.com/router5/redux-router5) into 2 repos, a deku and react version, which would mean you still only need 1 redux integration module, e.g.
- **React Redux Router5**
  react
  react-redux
  redux
  redux-router5 **changes to react-redux-router5**
  router5
- **Deku Redux Router5**
  deku
  deku-redux
  redux
  redux-router5 **changes to deku-redux-router5**
  router5

I am happy at the moment, with just adding a separate Link component, as it all seems to work well with this setup and I feel it is better than having an additional dependency. But I don't mind the idea of splitting redux-router5 into 2 repos. Linking in your examples is very easy with the named routes and passing the context.router through as props so it is easy enough to just add the Link component, if you think it removes the complexity of having 2 redux-router5 repos.

**Comment by troch** [comment] 2015-11-17 11:33
That got me thinking, so thank you for raising that issue :smile: :+1: .

I won't rename redux-router5 because both redux and router5 are view agnostic. That is not a definite no, but redux-router5 needs to evolve and mature a bit and I don't want to be left with two repos sharing the same code.

However, I think react-router5 and redux-router5 can provide the Link component, I just need to refactor. The problem is the current Link component being stateful. I need to make it stateless and provide a routeChange HOC which would add a route change listener and pass `route` as a prop to the Link. That will make things a lot more composable and reusable.

When using React (or deku) and router5 without redux:
- Your link component is Link + routeChange HOC (a named component should be created rather than leaving it up to the developer to have to do it all the time)
- If you have a menu and don't want to register a listener per link, you can use the stateless Link component and wrap your menu of links with routeChange HOC.

When using redux, nothing changes. Instead of using the routeChange HOC, you use the connect HOC. Whether you choose to bind to your state individual links or a menu of links or anything else...

:tada:

**Comment by svnm** [comment] 2015-11-18 01:24
I like the sound of the Link component being stateless, that makes sense to me. It would be great if within a redux/router5 app I could easily link to other containers as in a plan react/router5 app:

``` js
<Link routeName='product' routeParams={ id: product.id } >
{product.id}
</Link>
```

This currently works well in a plain react/router5 app but is more difficult when using redux. 

You mention a **routeChange HOC**. How does that work, would we still add the `<Link />` component when linking, and the **routeChange HOC** is just a wrapper around that?

When using redux, you mention that you can use the **connect HOC**. That sounds good, but I'm a bit confused on how it would work, I probably just need to see how you implement it.

For some background, at the moment the easiest way for me to link between containers in my redux/react/router5 app is to use the navigateTo action:

``` js
import { actions } from 'redux-router5';

function ProductContainer (props) {
  const { route } = props;

  return (
    <div onClick={ () => props.navigateActions.navigateTo('home') }>
    Link back to home
   </div>
  );
}

function mapDispatchToProps(dispatch) {
  return {
    ProductActions: bindActionCreators(ProductActions, dispatch),
    navigateActions: bindActionCreators(actions, dispatch)
  }
}

export default connect(routeNodeSelector('friends'), mapDispatchToProps)(ProductContainer)
```

**Comment by troch** [comment] 2015-11-18 10:00
> You mention a routeChange HOC. How does that work, would we still add the <Link /> component when linking, and the routeChange HOC is just a wrapper around that?

You would add a "Link" component (possibly named something else, see below). HOCs are not really wrappers, because they don't wrap a component instance. They are a component themselves using a base component to create an enhanced new Component `<Component> = <Component>(<Component>)`.

The use of `connect` or `routeChange` HOCs have the same goal: passing down `route` as a prop to a stateless Link component. The only difference is where it gets that `route` property from.

When using redux, it comes from your state (aka the single source of truth). `connect` subscribes to your store and passes down a portion of your state as props. If you follow instructions [here](https://github.com/router5/redux-router5), a connected Link component is defined by `const ConnectedLink = connect(state => state.router)(Link)`.

When not using redux and using router5 listeners plugin, it comes from the router directly. `routeChange` would register a route change listener with the router and pass down route change data to a component: `const ConnectedLink = routeChange(Link)`.

**Comment by troch** [comment] 2016-05-06 08:47
Closing this. react-router5 has `withRoute` and `routeNode` HOCs + a `BaseLink` component. It also has a `Link` component which is `withRoute` + `BaseLink`.

I use `BaseLink` with redux (it needs the router in context)

**Closed as completed by troch** 2016-05-06 08:47 UTC
